/** Auto-generated by scripts/genTokens.ts */
export interface DesignToken { value: string; layer: string }
export const tokens: Record<string, DesignToken> = {
    "--buig-palette-neutral-1": {
        "value": "#ffffff",
        "layer": "foundation"
    },
    "--buig-palette-neutral-2": {
        "value": "#f7f9fa",
        "layer": "foundation"
    },
    "--buig-palette-neutral-3": {
        "value": "#f2f4f6",
        "layer": "foundation"
    },
    "--buig-palette-neutral-4": {
        "value": "#e5e7eb",
        "layer": "foundation"
    },
    "--buig-palette-neutral-5": {
        "value": "#d1d5db",
        "layer": "foundation"
    },
    "--buig-palette-neutral-6": {
        "value": "#9ca3af",
        "layer": "foundation"
    },
    "--buig-palette-neutral-7": {
        "value": "#6b7280",
        "layer": "foundation"
    },
    "--buig-palette-neutral-8": {
        "value": "#4b5563",
        "layer": "foundation"
    },
    "--buig-palette-neutral-9": {
        "value": "#374151",
        "layer": "foundation"
    },
    "--buig-palette-neutral-10": {
        "value": "#111827",
        "layer": "foundation"
    },
    "--buig-palette-primary-1": {
        "value": "#eff6ff",
        "layer": "foundation"
    },
    "--buig-palette-primary-2": {
        "value": "#dbeafe",
        "layer": "foundation"
    },
    "--buig-palette-primary-3": {
        "value": "#bfdbfe",
        "layer": "foundation"
    },
    "--buig-palette-primary-4": {
        "value": "#93c5fd",
        "layer": "foundation"
    },
    "--buig-palette-primary-5": {
        "value": "#60a5fa",
        "layer": "foundation"
    },
    "--buig-palette-primary-6": {
        "value": "#3b82f6",
        "layer": "foundation"
    },
    "--buig-palette-primary-7": {
        "value": "#2563eb",
        "layer": "foundation"
    },
    "--buig-palette-primary-8": {
        "value": "#1d4ed8",
        "layer": "foundation"
    },
    "--buig-palette-primary-9": {
        "value": "#1e40af",
        "layer": "foundation"
    },
    "--buig-palette-primary-10": {
        "value": "#1e3a8a",
        "layer": "foundation"
    },
    "--buig-palette-success-5": {
        "value": "#16a34a",
        "layer": "foundation"
    },
    "--buig-palette-success-6": {
        "value": "#15803d",
        "layer": "foundation"
    },
    "--buig-palette-success-7": {
        "value": "#166534",
        "layer": "foundation"
    },
    "--buig-palette-warning-5": {
        "value": "#f59e0b",
        "layer": "foundation"
    },
    "--buig-palette-warning-6": {
        "value": "#d97706",
        "layer": "foundation"
    },
    "--buig-palette-warning-7": {
        "value": "#b45309",
        "layer": "foundation"
    },
    "--buig-palette-danger-5": {
        "value": "#dc2626",
        "layer": "foundation"
    },
    "--buig-palette-danger-6": {
        "value": "#b91c1c",
        "layer": "foundation"
    },
    "--buig-palette-danger-7": {
        "value": "#991b1b",
        "layer": "foundation"
    },
    "--buig-palette-info-5": {
        "value": "#0ea5e9",
        "layer": "foundation"
    },
    "--buig-palette-info-6": {
        "value": "#0284c7",
        "layer": "foundation"
    },
    "--buig-palette-info-7": {
        "value": "#0369a1",
        "layer": "foundation"
    },
    "--buig-radius-sm": {
        "value": "4px",
        "layer": "foundation"
    },
    "--buig-radius-md": {
        "value": "6px",
        "layer": "foundation"
    },
    "--buig-radius-lg": {
        "value": "8px",
        "layer": "foundation"
    },
    "--buig-radius-xl": {
        "value": "12px",
        "layer": "foundation"
    },
    "--buig-font-size-xs": {
        "value": "12px",
        "layer": "foundation"
    },
    "--buig-font-size-sm": {
        "value": "13px",
        "layer": "foundation"
    },
    "--buig-font-size-md": {
        "value": "14px",
        "layer": "foundation"
    },
    "--buig-font-size-lg": {
        "value": "16px",
        "layer": "foundation"
    },
    "--buig-line-height": {
        "value": "1.4",
        "layer": "foundation"
    },
    "--buig-spacing-1": {
        "value": "2px",
        "layer": "foundation"
    },
    "--buig-spacing-2": {
        "value": "4px",
        "layer": "foundation"
    },
    "--buig-spacing-3": {
        "value": "6px",
        "layer": "foundation"
    },
    "--buig-spacing-4": {
        "value": "8px",
        "layer": "foundation"
    },
    "--buig-spacing-5": {
        "value": "10px",
        "layer": "foundation"
    },
    "--buig-spacing-6": {
        "value": "12px",
        "layer": "foundation"
    },
    "--buig-spacing-7": {
        "value": "14px",
        "layer": "foundation"
    },
    "--buig-spacing-8": {
        "value": "16px",
        "layer": "foundation"
    },
    "--buig-spacing-9": {
        "value": "20px",
        "layer": "foundation"
    },
    "--buig-spacing-10": {
        "value": "24px",
        "layer": "foundation"
    },
    "--buig-shadow-pop": {
        "value": "0 6px 20px rgba(0, 0, 0, 0.15)",
        "layer": "foundation"
    },
    "--buig-shadow-overlay": {
        "value": "0 10px 30px rgba(0, 0, 0, 0.2)",
        "layer": "foundation"
    },
    "--buig-motion-fast": {
        "value": "80ms",
        "layer": "foundation"
    },
    "--buig-motion-base": {
        "value": "160ms",
        "layer": "foundation"
    },
    "--buig-motion-slow": {
        "value": "240ms",
        "layer": "foundation"
    },
    "--buig-ease-in-out": {
        "value": "cubic-bezier(0.4, 0, 0.2, 1)",
        "layer": "foundation"
    },
    "--buig-ease-out": {
        "value": "cubic-bezier(0, 0, 0.2, 1)",
        "layer": "foundation"
    },
    "--buig-ease-in": {
        "value": "cubic-bezier(0.4, 0, 1, 1)",
        "layer": "foundation"
    },
    "--buig-z-base": {
        "value": "0",
        "layer": "foundation"
    },
    "--buig-z-dropdown": {
        "value": "1000",
        "layer": "foundation"
    },
    "--buig-z-sticky": {
        "value": "1100",
        "layer": "foundation"
    },
    "--buig-z-fixed": {
        "value": "1200",
        "layer": "foundation"
    },
    "--buig-z-popup": {
        "value": "1300",
        "layer": "foundation"
    },
    "--buig-z-modal": {
        "value": "1400",
        "layer": "foundation"
    },
    "--buig-z-toast": {
        "value": "1500",
        "layer": "foundation"
    },
    "--buig-color-bg": {
        "value": "var(--buig-palette-neutral-1)",
        "layer": "semantic"
    },
    "--buig-color-bg-subtle": {
        "value": "var(--buig-palette-neutral-2)",
        "layer": "semantic"
    },
    "--buig-color-bg-muted": {
        "value": "var(--buig-palette-neutral-3)",
        "layer": "semantic"
    },
    "--buig-color-border": {
        "value": "var(--buig-palette-neutral-4)",
        "layer": "semantic"
    },
    "--buig-color-border-subtle": {
        "value": "var(--buig-palette-neutral-3)",
        "layer": "semantic"
    },
    "--buig-color-text": {
        "value": "var(--buig-palette-neutral-9)",
        "layer": "semantic"
    },
    "--buig-color-text-secondary": {
        "value": "var(--buig-palette-neutral-7)",
        "layer": "semantic"
    },
    "--buig-color-primary": {
        "value": "var(--buig-palette-primary-6)",
        "layer": "semantic"
    },
    "--buig-color-primary-hover": {
        "value": "var(--buig-palette-primary-7)",
        "layer": "semantic"
    },
    "--buig-color-primary-active": {
        "value": "var(--buig-palette-primary-8)",
        "layer": "semantic"
    },
    "--buig-color-primary-disabled": {
        "value": "var(--buig-palette-primary-3)",
        "layer": "semantic"
    },
    "--buig-color-primary-foreground": {
        "value": "#ffffff",
        "layer": "semantic"
    },
    "--buig-color-success": {
        "value": "var(--buig-palette-success-5)",
        "layer": "semantic"
    },
    "--buig-color-success-hover": {
        "value": "var(--buig-palette-success-6)",
        "layer": "semantic"
    },
    "--buig-color-success-active": {
        "value": "var(--buig-palette-success-7)",
        "layer": "semantic"
    },
    "--buig-color-success-foreground": {
        "value": "#ffffff",
        "layer": "semantic"
    },
    "--buig-color-warning": {
        "value": "var(--buig-palette-warning-5)",
        "layer": "semantic"
    },
    "--buig-color-warning-hover": {
        "value": "var(--buig-palette-warning-6)",
        "layer": "semantic"
    },
    "--buig-color-warning-active": {
        "value": "var(--buig-palette-warning-7)",
        "layer": "semantic"
    },
    "--buig-color-warning-foreground": {
        "value": "#ffffff",
        "layer": "semantic"
    },
    "--buig-color-danger": {
        "value": "var(--buig-palette-danger-5)",
        "layer": "semantic"
    },
    "--buig-color-danger-hover": {
        "value": "var(--buig-palette-danger-6)",
        "layer": "semantic"
    },
    "--buig-color-danger-active": {
        "value": "var(--buig-palette-danger-7)",
        "layer": "semantic"
    },
    "--buig-color-danger-foreground": {
        "value": "#ffffff",
        "layer": "semantic"
    },
    "--buig-color-neutral": {
        "value": "var(--buig-palette-neutral-3)",
        "layer": "semantic"
    },
    "--buig-color-neutral-hover": {
        "value": "var(--buig-palette-neutral-4)",
        "layer": "semantic"
    },
    "--buig-color-neutral-active": {
        "value": "var(--buig-palette-neutral-5)",
        "layer": "semantic"
    },
    "--buig-color-neutral-foreground": {
        "value": "var(--buig-palette-neutral-8)",
        "layer": "semantic"
    },
    "--buig-control-font-size-xs": {
        "value": "var(--buig-font-size-xs)",
        "layer": "semantic"
    },
    "--buig-control-font-size-sm": {
        "value": "13px",
        "layer": "semantic"
    },
    "--buig-control-font-size-md": {
        "value": "var(--buig-font-size-md)",
        "layer": "semantic"
    },
    "--buig-control-font-size-lg": {
        "value": "15px",
        "layer": "semantic"
    },
    "--buig-control-height-xs": {
        "value": "24px",
        "layer": "semantic"
    },
    "--buig-control-height-sm": {
        "value": "28px",
        "layer": "semantic"
    },
    "--buig-control-height-md": {
        "value": "34px",
        "layer": "semantic"
    },
    "--buig-control-height-lg": {
        "value": "40px",
        "layer": "semantic"
    },
    "--buig-control-padding-x-xs": {
        "value": "8px",
        "layer": "semantic"
    },
    "--buig-control-padding-x-sm": {
        "value": "10px",
        "layer": "semantic"
    },
    "--buig-control-padding-x-md": {
        "value": "14px",
        "layer": "semantic"
    },
    "--buig-control-padding-x-lg": {
        "value": "16px",
        "layer": "semantic"
    },
    "--buig-control-padding-y-xs": {
        "value": "4px",
        "layer": "semantic"
    },
    "--buig-control-padding-y-sm": {
        "value": "6px",
        "layer": "semantic"
    },
    "--buig-control-padding-y-md": {
        "value": "8px",
        "layer": "semantic"
    },
    "--buig-control-padding-y-lg": {
        "value": "10px",
        "layer": "semantic"
    },
    "--buig-control-radius-xs": {
        "value": "6px",
        "layer": "semantic"
    },
    "--buig-control-radius-sm": {
        "value": "6px",
        "layer": "semantic"
    },
    "--buig-control-radius-md": {
        "value": "8px",
        "layer": "semantic"
    },
    "--buig-control-radius-lg": {
        "value": "10px",
        "layer": "semantic"
    },
    "--buig-button-height-md": {
        "value": "var(--buig-control-height-md)",
        "layer": "component"
    },
    "--buig-button-padding-x-md": {
        "value": "var(--buig-control-padding-x-md)",
        "layer": "component"
    },
    "--buig-button-radius": {
        "value": "var(--buig-control-radius-md)",
        "layer": "component"
    },
    "--buig-button-font-size": {
        "value": "var(--buig-control-font-size-md)",
        "layer": "component"
    },
    "--buig-button-bg": {
        "value": "var(--buig-color-primary)",
        "layer": "component"
    },
    "--buig-button-bg-hover": {
        "value": "var(--buig-color-primary-hover)",
        "layer": "component"
    },
    "--buig-button-bg-active": {
        "value": "var(--buig-color-primary-active)",
        "layer": "component"
    },
    "--buig-button-bg-disabled": {
        "value": "var(--buig-color-primary-disabled)",
        "layer": "component"
    },
    "--buig-button-fg": {
        "value": "var(--buig-color-primary-foreground)",
        "layer": "component"
    },
    "--buig-button-shadow-focus": {
        "value": "0 0 0 3px rgba(59, 130, 246, 0.35)",
        "layer": "component"
    },
    "--buig-input-height-md": {
        "value": "var(--buig-control-height-md)",
        "layer": "component"
    },
    "--buig-input-padding-x-md": {
        "value": "var(--buig-control-padding-x-md)",
        "layer": "component"
    },
    "--buig-input-radius": {
        "value": "var(--buig-control-radius-md)",
        "layer": "component"
    },
    "--buig-input-font-size": {
        "value": "var(--buig-control-font-size-md)",
        "layer": "component"
    },
    "--buig-input-bg": {
        "value": "var(--buig-color-bg)",
        "layer": "component"
    },
    "--buig-input-border": {
        "value": "var(--buig-color-border)",
        "layer": "component"
    },
    "--buig-input-border-hover": {
        "value": "var(--buig-color-primary-hover)",
        "layer": "component"
    },
    "--buig-input-border-focus": {
        "value": "var(--buig-color-primary)",
        "layer": "component"
    },
    "--buig-input-fg": {
        "value": "var(--buig-color-text)",
        "layer": "component"
    },
    "--buig-input-placeholder": {
        "value": "var(--buig-color-text-secondary)",
        "layer": "component"
    },
    "--buig-input-shadow-focus": {
        "value": "0 0 0 2px rgba(59, 130, 246, 0.25)",
        "layer": "component"
    },
    "--buig-card-bg": {
        "value": "var(--buig-color-bg)",
        "layer": "component"
    },
    "--buig-card-border": {
        "value": "var(--buig-color-border-subtle)",
        "layer": "component"
    },
    "--buig-card-radius": {
        "value": "var(--buig-radius-lg, 8px)",
        "layer": "component"
    },
    "--buig-card-padding-x": {
        "value": "var(--buig-spacing-8)",
        "layer": "component"
    },
    "--buig-card-padding-y": {
        "value": "var(--buig-spacing-7)",
        "layer": "component"
    },
    "--buig-card-shadow": {
        "value": "var(--buig-shadow-pop)",
        "layer": "component"
    },
    "--buig-select-height-md": {
        "value": "var(--buig-control-height-md)",
        "layer": "component"
    },
    "--buig-select-radius": {
        "value": "var(--buig-control-radius-md)",
        "layer": "component"
    },
    "--buig-select-font-size": {
        "value": "var(--buig-control-font-size-md)",
        "layer": "component"
    },
    "--buig-select-bg": {
        "value": "var(--buig-color-bg)",
        "layer": "component"
    },
    "--buig-select-border": {
        "value": "var(--buig-color-border)",
        "layer": "component"
    },
    "--buig-select-border-hover": {
        "value": "var(--buig-color-primary-hover)",
        "layer": "component"
    },
    "--buig-select-border-focus": {
        "value": "var(--buig-color-primary)",
        "layer": "component"
    },
    "--buig-select-dropdown-bg": {
        "value": "var(--buig-color-bg)",
        "layer": "component"
    },
    "--buig-select-dropdown-border": {
        "value": "var(--buig-color-border-subtle)",
        "layer": "component"
    },
    "--buig-select-option-hover-bg": {
        "value": "var(--buig-color-neutral-hover)",
        "layer": "component"
    },
    "--buig-select-option-active-bg": {
        "value": "var(--buig-color-primary)",
        "layer": "component"
    },
    "--buig-select-option-active-fg": {
        "value": "var(--buig-color-primary-foreground)",
        "layer": "component"
    },
    "--buig-tag-radius": {
        "value": "var(--buig-radius-sm)",
        "layer": "component"
    },
    "--buig-tag-font-size": {
        "value": "var(--buig-font-size-sm)",
        "layer": "component"
    },
    "--buig-tag-padding-x": {
        "value": "var(--buig-spacing-4)",
        "layer": "component"
    },
    "--buig-tag-padding-y": {
        "value": "var(--buig-spacing-2)",
        "layer": "component"
    },
    "--buig-tag-bg": {
        "value": "var(--buig-color-neutral)",
        "layer": "component"
    },
    "--buig-tag-bg-hover": {
        "value": "var(--buig-color-neutral-hover)",
        "layer": "component"
    },
    "--buig-tag-fg": {
        "value": "var(--buig-color-neutral-foreground)",
        "layer": "component"
    },
    "--buig-tag-border": {
        "value": "var(--buig-color-border-subtle)",
        "layer": "component"
    },
    "--buig-alert-radius": {
        "value": "var(--buig-radius-md)",
        "layer": "component"
    },
    "--buig-alert-padding-x": {
        "value": "var(--buig-spacing-8)",
        "layer": "component"
    },
    "--buig-alert-padding-y": {
        "value": "var(--buig-spacing-6)",
        "layer": "component"
    },
    "--buig-alert-bg-info": {
        "value": "var(--buig-color-info, var(--buig-color-primary))",
        "layer": "component"
    },
    "--buig-alert-bg-success": {
        "value": "var(--buig-color-success)",
        "layer": "component"
    },
    "--buig-alert-bg-warning": {
        "value": "var(--buig-color-warning)",
        "layer": "component"
    },
    "--buig-alert-bg-danger": {
        "value": "var(--buig-color-danger)",
        "layer": "component"
    },
    "--buig-alert-fg": {
        "value": "#fff",
        "layer": "component"
    },
    "--buig-alert-shadow": {
        "value": "var(--buig-shadow-pop)",
        "layer": "component"
    }
};
export type TokenName = keyof typeof tokens;
